CREATE TABLE VEHICLE (
VEHICLE_NO VARCHAR(10) NOT NULL,
COLOR VARCHAR(10),
WHEEL INT,
SEAT INT,
PRIMARY KEY (VEHICLE_NO)
);

CREATE TABLE ACCOUNT (
  ACCOUNT_NO VARCHAR(10) NOT NULL,
  BALANCE DOUBLE NOT NULL,
  PRIMARY KEY (ACCOUNT_NO)
);
